#!/usr/bin/env python
#
# Deactivates an existing music directory: stops the associated daemons,
# unmounts the audio filesystems and unmounts any cache filesystems.
#
# See activate-music-directory, dismantle-music-directory.
#
# Copyright (C) James MacKay 2008
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from audiofs import admin, config


# Constants.

_conf = config.obtain()


# Classes.

class Program(admin.ad_AbstractMusicDirectoryProgram):
    """
    Represents programs that deactivate a music directory.
    """

    def _ad_mainUsageDescription(self):
        result = """which deactivates the music directory '%s':
all associated daemon processes are stopped, the audio
filesystems are unmounted, and any cache filesystems are
unmounted.""" % _conf.rootDir
        assert result
        return result

    def _ad_administer(self, ad, argsMap):
        assert ad is not None
        assert argsMap is not None
        ad.ad_deactivateMusicDirectory()

Program().run()
