#!/usr/bin/env python
#
# Copyright (C) James MacKay 2008
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from audiofs import flac2oggfs

flac2oggfs.main()

# In order to profile this filesystem comment out the above call to
# main() and uncomment all of the following lines:
#import profile
#import config
#import os.path
#profile.Profile.bias = 2.4799752002478521e-05
#profile.run("flac2oggfs.main()", os.path.join(config.obtain().metadataDir, "profile-flac2oggfs.data"))
